name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read PACKAGES file
        id: packages
        run: | 
            echo 'deps<<EOF' >> "$GITHUB_OUTPUT"
            cat PACKAGES | grep -v ^# >> "$GITHUB_OUTPUT"
            echo 'EOF' >> "$GITHUB_OUTPUT"
      - name: Update r installation
        uses: grady/r-lib-actions/setup-r@v2-branch
      - name: Install dependencies from PACKAGES
        uses: grady/r-lib-actions/setup-r-dependencies@v2-branch
        with:
          dependencies: 'NA'
          packages: |
            dplyr
            jsonlite
            testthat
            readr
            rmarkdown
            tidyr
            ${{ steps.packages.outputs.deps }}
      - name: Execute tests.R
        run: |
            # Execute tests.R
            cat("::group::Running tests\n")
            test_results <- as.data.frame(testthat::test_file("tests.R"))
            cat("::endgroup::\n")
            cat("::group::Writing autograding.json\n")
            fp <- file.path(".github", "classroom", "autograding.json")
            dir.create(dirname(fp))
            separate_regex <- c("<?", points="[0-9]*", ">?", name=".*")
            format_result <- function(res){
              trimws(paste(lapply(res, as.character), collapse="\n"))
            }
            output_df <- dplyr::transmute(
              tidyr::separate_wider_regex(test_results, test, separate_regex),
              name, points=as.integer(points), run=tolower(!failed),
              setup=paste0("echo -n '", sapply(result,format_result), "'"))
            write(jsonlite::toJSON(list(tests=output_df)), fp)
            cat("::endgroup::\n")
            cat("::group::Generated autograding.json\n")
            writeLines(jsonlite::prettify(readr::read_file(fp)))
            cat("::endgroup::\n")
        shell: Rscript {0}
      - name: Github Classroom autograder
        uses: education/autograding@v1
        